fixtures:
  symlinks:
    bareos: "#{source_dir}"
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "2.2.1"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "3.2.2"
